server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/maidejiainfo?serverTimezone=PRC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      # 设置热部署生效
      enabled: true
      # 设置重启的目录
      additional-paths: src/main/java
      # WEB-INF目录下内容发生更改不重启
      exclude: WEB-INF/*
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  security:
    user:
      name: root
      password: root


