server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=PRC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      # 设置热部署生效
      enabled: true
      # 设置重启的目录
      additional-paths: src/main/java
      # WEB-INF目录下内容发生更改不重启
      exclude: WEB-INF/*
  # 格式化时间
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  security:
    user:
      name: root
      password: root
  jpa:
    open-in-view: false #操作数据库的连接文件
  # 自定义404 出现错误时, 直接抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
  #不要为我们工程中的资源文件建立映射
  web:
    resources:
      add-mappings: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.Entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
#showSql
logging:
  level:
    com:
      example:
        demo:
          mapper: debug

